# At some point, should probably change to generic (since using conda)
language: python

sudo: false

# TODO: various temp things in this PR for testing; will be undone
# before merge.

stages:
  - test
  - name: docs
    if: (branch != packaging)
  - name: conda_dev_package
    if: (branch = packaging)


jobs:
  include:
    - &default
      stage: test
      python: "2.7"
#      before_install:
#        #########################
#        ##### install conda #####
#        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
#        - bash miniconda.sh -b -p $HOME/miniconda
#        - export PATH="$HOME/miniconda/bin:$PATH"
#        - hash -r
#        - conda config --set always_yes yes --set changeps1 no
#        - conda update -q conda
#        # Useful for debugging any issues with conda
#        - conda info -a
#        #########################       
#        - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
#        - source activate test-environment
      install: true
#        - conda install -c conda-forge nose numpy matplotlib bokeh pandas scipy jupyter ipython param flake8 mock filelock iris cartopy xarray geopandas numpy shapely=1.6.3 gdal=2.2.3 libgdal=2.2.3 glib=2.55.0 gstreamer=1.8.0 datashader --quiet
#        - pip install coveralls
#        - pip install git+https://github.com/ioam/holoviews.git
#        - python setup.py install
      script: true
#        - nosetests --with-doctest --with-coverage --cover-package=geoviews
#        - flake8 --ignore=E,W . --exclude=./doc

#    - <<: *default
#      python: "3.6"
#      after_success: coveralls      

    - <<: *default
      stage: docs
      python: "3.6"
      script:
        # TODO: can't remember why I did this twice
        - python -c "import geoviews as gv; gv.sample_data('notebooks/user_guide/sample-data')"
        - python -c "import geoviews as gv; gv.sample_data('doc/sample-data')"
        - conda install -c conda-forge sphinx<1.7 beautifulsoup4 graphviz
        - conda install -c nesii/label/dev-esmf -c conda-forge esmpy
        - pip install xesmf
        - pip install nbsite
        - pip install sphinx_ioam_theme
        # TODO: should make this content available too rather than deleting it!
        - rm notebooks/*.ipynb
        - cd doc
        - nbsite_nbpagebuild.py ioam geoviews ../notebooks .
        - sphinx-build -b html . ./_build/html
        - nbsite_fix_links.py _build/html
        - nbsite_cleandisthtml.py ./_build/html take_a_chance
        - cp -r ../notebooks/user_guide/assets _build/html/user_guide/
        - cp -r ../notebooks/user_guide/sample-data _build/html/user_guide/
        - touch ./_build/html/.nojekyll
        - cd ..
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: ./doc/_build/html
        on:
          tags: true

    - &conda_default
      stage: conda_dev_package
      python: 3.6
      before_install:
        - pip install pyct && doit install_miniconda && rm -f .doit.db
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda install -y -c pyviz/label/dev -c conda-forge pyct
        - doit ci_configure_conda
      install:
        - export VERSIONHACK=$(python -c "import subprocess;desc=subprocess.check_output(['git','describe','--long']).decode('utf8');v,commits=desc.split('-')[0:2];newv=[int(x) for x in v.split('.')];newv[-1]+=1;print('.'.join(str(x) for x in newv)+'.dev'+commits)")      
        - doit build_conda_package --channel ioam --channel conda-forge
      script: true
#        - doit upload_conda_package --token=$CONDA_UPLOAD_TOKEN
#  
#    - <<: *conda_default
#      stage: conda_package
#      script:
#        - doit upload_conda_package --token=$CONDA_UPLOAD_TOKEN --label=main --label=dev
